- name: Install development packages
  apt:
    name: byobu,git,vim-nox
    state: present
  become: true

- name: Copy dotfiles into place
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
  with_items:
    - { src: 'bash_aliases', dest: '/home/{{ username }}/.bash_aliases' }
    - { src: 'bashrc', dest: '/home/{{ username }}/.bashrc' }
    - { src: 'zshrc', dest: '/home/{{ username }}/.zshrc' }
    - { src: 'bash_git', dest: '/home/{{ username }}/.bash_git' }
    - { src: 'bash_git_ps1', dest: '/home/{{ username }}/.bash_git_ps1' }
    - { src: 'vimrc.spf13', dest: '/home/{{ username }}/.vimrc' }
    - { src: 'vimrc.before', dest: '/home/{{ username }}/.vimrc.before' }
    - { src: 'vimrc.local', dest: '/home/{{ username }}/.vimrc.local' }
    - { src: 'vimrc.bundles', dest: '/home/{{ username }}/.vimrc.bundles' }
  become: true
  become_user: "{{ username }}"

- name: Render dotfile templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
  with_items:
    - { src: 'gitconfig.jinja2', dest: '/home/{{ username }}/.gitconfig' }
  become: true
  become_user: "{{ username }}"

- name: Install Vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: /home/{{ username }}/.vim/bundle/Vundle.vim
  become: true
  become_user: "{{ username }}"

- name: Install Vundle plugins
  command: vim +PluginInstall +qall
  become: true
  become_user: "{{ username }}"

- name: Install zsh-vi-mode plugin
  git:
    repo: https://github.com/jeffreytse/zsh-vi-mode
    dest: /home/{{ username }}/.oh-my-zsh/custom/plugins/zsh-vi-mode
  become: true
  become_user: "{{ username }}"
