- name: Install development packages
  apt:
    name: ack-grep,byobu,bzr,git,virtualenv,vim-nox,golang-1.8,docker.io
    state: present
  become: true

- name: Create required directories
  file:
    path: '/home/{{ username }}/.bazaar/plugins'
    state: directory
    owner: '{{ username }}'
    group: '{{ username }}'
    recurse: yes

- name: Copy dotfiles into place
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
  with_items:
    - { src: 'bash_aliases', dest: '/home/{{ username }}/.bash_aliases' }
    - { src: 'bashrc', dest: '/home/{{ username }}/.bashrc' }
    - { src: 'bash_git', dest: '/home/{{ username }}/.bash_git' }
    - { src: 'bash_git_ps1', dest: '/home/{{ username }}/.bash_git_ps1' }
    - { src: 'vimrc.spf13', dest: '/home/{{ username }}/.vimrc' }
    - { src: 'vimrc.before', dest: '/home/{{ username }}/.vimrc.before' }
    - { src: 'vimrc.local', dest: '/home/{{ username }}/.vimrc.local' }
    - { src: 'vimrc.bundles', dest: '/home/{{ username }}/.vimrc.bundles' }
  become: true

- name: Render dotfile templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
  with_items:
    - { src: 'gitconfig.jinja2', dest: '/home/{{ username }}/.gitconfig' }
    - { src: 'bzrconfig.jinja2', dest: '/home/{{ username }}/.bazaar/bazaar.conf' }
    - { src: 'bzrauthconfig.jinja2', dest: '/home/{{ username }}/.bazaar/authentication.conf' }
  become: true

- name: Install Vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: /home/{{ username }}/.vim/bundle/Vundle.vim
  become: true

- name: Ensure ownership for Vundle bundles directory
  file:
    dest: /home/{{ username }}/.vim/bundle
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0775
  become: true

- name: Install Vundle plugins
  command: vim +PluginInstall +qall
  become: true
  become_user: "{{ username }}"
